apiVersion: v1
kind: Secret
stringData:
  enableOCI: "true"
  name: helm-ecr
  type: helm
  url: 863422182520.dkr.ecr.ap-northeast-2.amazonaws.com
  username: AWS
  password: ""
metadata:
  labels:
    argocd-ecr-updater: enabled
    argocd.argoproj.io/secret-type: repository
  name: helm-ecr
  namespace: argocd
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: ""